# .github/workflows/deploy.yml

name: Deploy S3 Bucket with Terraform

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true
        default: 'v1.0.0'  # Default value (optional)

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan the Terraform deployment
      - name: Terraform Plan
        run: terraform plan -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}" -var="tag=${{ github.event.inputs.tag }}"

      # Apply the Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}" -var="tag=${{ github.event.inputs.tag }}"
